### ISSUE TITLE
init Project

### ISSUE THREAD

**Issue by marvelsrp** [juks/HomeMeter#2]
Привет. Решил поднять твой проект для считывания показаний импульсного счетчика воды. Не получается установить зависимости через npm install. 
Ругается на rpi-gpio
`.node-gyp/9.2.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’`
Обновил все модули, все вроде поставилось, но запустить так и не удалось, видимо rpi-grio только под малинкой работает. Ты когда разрабатывал, моки ставил, или сразу на малинке писал?

**Comment by juks** [comment]
Привет! Я подключал IDE через sftp непосредственно к устройству. Соответственно, всё работало только так.

**Comment by marvelsrp** [comment]
Привет, как успехи с проектом? Работает стабильно? Были ли дополнительные сложности?

**Comment by marvelsrp** [comment]
Скинь пожалуйста ссылку на статью

**Comment by juks** [comment]
Какую именно статью?

**Comment by marvelsrp** [comment]
Мне казалось ты на хабре писал про этот проект, не?

**Comment by juks** [comment]
Я точно не писал :-)

**Comment by marvelsrp** [comment]
Подскажи пожалуйста, какого номинала резистор ставил?

**Comment by juks** [comment]
10 кОм
